/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes.gen";
import runner from "./pages/JourneyRunner";

function journey() {
  QUnit.module("SpacefarersObjectPageObjectPage journey");

  opaTest(
    "Navigate to SpacefarersObjectPageObjectPage",
    function (Given: Given, When: When, Then: Then) {
      Given.iStartMyApp();
      When.onTheSpacefarersListGenerated.onFilterBar().iExecuteSearch();
      Then.onTheSpacefarersListGenerated.onTable("").iCheckRows();
      When.onTheSpacefarersListGenerated.onTable("").iPressRow(0);

      Then.onTheSpacefarersObjectPageGenerated.iSeeThisPage();
    },
  );

  opaTest("Teardown", function (Given: Given) {
    // Cleanup
    Given.iTearDownMyApp();
  });
}

runner.run([journey]);
